### Get all shopping lists
GET http://localhost:3000/shoppinglists

### Add shopping list 
POST http://localhost:3000/shoppinglists
Content-Type: application/json

{
"name": "Harris Teeter"
}

### Get shopping list by id
GET http://localhost:3000/shoppinglists/65c2e33f8ada7625db7fba22

### test get one bookmark with an object id not in the db (right length), just doesn't exist) 
GET http://localhost:3000/shoppinglists/65b30f8ace943ee2ba7e38b5

### test get one bookmark with an invalid object id (not the right length) 
GET http://localhost:3000/shoppinglists/blurb

### TODO: update one bookmark 
PATCH http://localhost:3000/shoppinglists/65c2f6d1d7b8ca7c3ac94ade
Content-Type: application/json

{
"name": "Harris Teeter 2"
}

### TODO: delete one bookmark 
DELETE http://localhost:3000/shoppinglists/65c2e3b28ada7625db7fba27

### TODO: get one bookmark by title GET http://localhost:3000/shoppinglists/google