### GET all shopping lists
GET http://localhost:3000/shoppinglists

### GET shopping list by shoppingListId
GET http://localhost:3000/shoppinglists/65ce76e26007b64f6b2ee1d4

### GET response "Shop not found" test get one store with an object id not in the db (right length), just doesn't exist) 
GET http://localhost:3000/shoppinglists/65cc037b0fbb27a613945500

### GET response "Bad request" test get one store with an invalid object id (not the right length) 
GET http://localhost:3000/shoppinglists/65cc

### POST shopping list 
POST http://localhost:3000/shoppinglists
Content-Type: application/json

{
"storeName": "Walmart"
}

### POST item 
POST http://localhost:3000/shoppinglists/65ce7febc7763a356d1a7066/items
Content-Type: application/json

{
"itemName": "icecream",
"quantity": "2",
"purchased": false
}

### PATCH one shopping list 
PATCH http://localhost:3000/shoppinglists/65ce7febc7763a356d1a7066
Content-Type: application/json

{
"storeName": "Grocery Store 3"
}

### PATCH one item 
PATCH http://localhost:3000/shoppinglists/65ce7febc7763a356d1a7066/items/65ce8216f1d7bcef85809ac8
Content-Type: application/json

{
"itemName": "Kondike bar",
"quantity": "20"
}

### DELETE one store  
DELETE http://localhost:3000/shoppinglists/65ce775d6007b64f6b2ee1eb

### DELETE one item  
DELETE http://localhost:3000/shoppinglists/65ce76e26007b64f6b2ee1d4/items/65ce79866226e24416488312

### TODO: get one bookmark by title GET http://localhost:3000/shoppinglists/google