### Get all shopping lists
GET http://localhost:3000/shoppinglists

### Add shopping list 
POST http://localhost:3000/shoppinglists
Content-Type: application/json

{
"name": "Costco"
}

### get one bookmark by id GET http://localhost:3000/shoppinglists/65bc433d6097a46e9ac86795

### test get one bookmark with an object id not in the db (right length), just doesn't exist) GET http://localhost:3000/shoppinglists/65b30f8ace943ee2ba7e38b5

### test get one bookmark with an invalid object id (not the right length) GET http://localhost:3000/shoppinglists/blurb

### TODO: update one bookmark PATCH http://localhost:3000/shoppinglists/65bc433d6097a46e9ac86795 Content-Type: application/json

# {
# "url": "https://drawing.garden/", "title": "Emoji Garden 🌱"
# }

### TODO: delete one bookmark DELETE http://localhost:3000/shoppinglists/65b30f8ace943ee2ba7e38b3

### TODO: get one bookmark by title GET http://localhost:3000/shoppinglists/google